version: '3.1'

services:

  db:
    image: mongo
    container_name: mongo-payloadcms
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    volumes:
      - ./mongo:/data/db